import Link from 'next/link';
import type {Params,Place,Region} from './types';

export const labels:Record<string,string>={free:'무료',kids:'아이와 함께',pet:'반려동물 동반',indoor:'실내'};
export const collections:Record<string,string>={today:'오늘 열리는 행사',weekend:'이번 주말 행사',free:'무료로 즐기는 여행',kids:'아이와 함께 갈 곳',pet:'반려동물과 함께',indoor:'비 오는 날 실내 여행'};
export function value(params:Params,key:string){const val=params[key];return Array.isArray(val)?val[0]||'':val||'';}
export function detailPath(p:Place){return `${p.kind==='festival'?'/festival/':'/place/'}${p.id}`;}
export function formatDate(input:string|null|undefined){if(!input)return '확인 필요';return new Date(input).toLocaleDateString('ko-KR',{timeZone:'Asia/Seoul',year:'numeric',month:'long',day:'numeric'});}
export function SearchForm({regions,params={},target='/search',compact=false}:{regions:Region[];params?:Params;target?:string;compact?:boolean}){
  return <form action={target} className={`search-form ${compact?'compact':''}`}><label className="search-input"><span aria-hidden="true">⌕</span><input name="q" aria-label="지역·장소 검색" placeholder="어디로 떠나고 싶으세요?" defaultValue={value(params,'q')} maxLength={200}/></label><label className="sr-only" htmlFor="region-select">지역</label><select id="region-select" name="region" defaultValue={value(params,'region')}><option value="">전국 모든 지역</option>{regions.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select>{compact&&<><label className="sr-only" htmlFor="condition-select">여행 조건</label><select id="condition-select" name="condition" defaultValue={value(params,'condition')}><option value="">모든 조건</option>{Object.entries(labels).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select><label className="sr-only" htmlFor="date-select">행사 날짜</label><select id="date-select" name="when" defaultValue={value(params,'when')}><option value="">날짜 선택</option><option value="today">오늘 행사</option><option value="weekend">이번 주말 행사</option></select></>}<button type="submit">검색</button></form>;
}

export function Card({place,base=''}:{place:Place;base?:string}){
  const tags=Object.entries(place.conditions).filter(([,v])=>v===true);
  return <Link className={`place-card ${place.kind}`} href={`${base}${detailPath(place)}`}><div className="card-top"><span className="card-category">{place.kind==='festival'?'FESTIVAL':'PLACE'}</span><span className="card-symbol" aria-hidden="true">{place.kind==='festival'?'✳':place.conditions.indoor?'▤':'⌖'}</span></div>{place.images?.[0]&&<figure className="card-photo"><img src={place.images[0].url} alt={place.images[0].alt} loading="lazy"/><figcaption>{place.images[0].credit} · {place.images[0].license}</figcaption></figure>}<div className="card-content"><div className="card-region">{place.region_name.split(' ').slice(-1)}</div><h3>{place.name}</h3>{place.start_date&&<p className="event-date">{place.start_date} — {place.end_date}{place.event_status==='ended'&&' · 종료'}</p>}<p className="card-address">{place.address}</p><div className="tags">{tags.map(([k])=><span key={k}>{labels[k]}</span>)}{tags.length===0&&<span className="unknown">조건 확인 필요</span>}</div><div className="card-bottom"><span>{place.is_demo?'샘플 데이터':place.verified_at?`${formatDate(place.verified_at)} 확인`:'한국관광공사 공식 데이터'}</span>{place.distance_km!==undefined&&<strong>직선 {place.distance_km}km</strong>}</div></div></Link>;
}
export function Cards({items,base=''}:{items:Place[];base?:string}){return items.length?<div className="cards">{items.map(p=><Card place={p} base={base} key={p.id}/>)}</div>:<div className="empty"><span>⌕</span><h3>조건에 맞는 정보가 아직 없습니다</h3><p>다른 지역이나 조건을 선택해 보세요.</p></div>;}
