'use client';
import {useState} from 'react';
type Item={id:string;kind:'place'|'festival';evidence:Record<string,{source:string}>;name:string;address:string;status:string;quality_score:number;conditions:Record<string,boolean|null>;source_hidden:boolean};
const labels:Record<string,string>={free:'무료',kids:'아이와 함께',pet:'반려동물 동반',indoor:'실내'};
export function Reviews({token}:{token:string}){
 const [items,setItems]=useState<Item[]>([]),[selected,setSelected]=useState<Item|null>(null),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 async function load(){setBusy(true);try{const r=await fetch('/api/admin?view=queue',{headers:{'x-admin-token':token},cache:'no-store'});const d=await r.json();if(!r.ok)throw Error(typeof d.detail==='string'?d.detail:'조회 실패');setItems(d.items);}catch(e){setMessage(e instanceof Error?e.message:'조회 실패');}finally{setBusy(false);}}
 async function save(event:React.FormEvent<HTMLFormElement>){event.preventDefault();if(!selected)return;const form=event.currentTarget;const data=new FormData(form);const action=(event.nativeEvent as SubmitEvent).submitter?.getAttribute('value')||'approve';const conditions=Object.fromEntries(Object.keys(labels).map(key=>[key,{value:data.get(key)==='unknown'?null:data.get(key)==='true',source:String(data.get(key+'_source')||'')} ]));setBusy(true);setMessage('');try{const r=await fetch('/api/admin',{method:'POST',headers:{'x-admin-token':token,'Content-Type':'application/json'},body:JSON.stringify({place_id:selected.id,action,reviewer:data.get('reviewer'),note:data.get('note'),content_checked:data.has('content_checked'),boundary_checked:data.has('boundary_checked'),conditions})});const d=await r.json();if(!r.ok)throw Error(typeof d.detail==='string'?d.detail:'입력값과 확인 근거를 확인하세요.');setSelected(null);setMessage('검수 결과를 새 데이터 버전으로 저장했습니다.');await load();}catch(e){setMessage(e instanceof Error?e.message:'저장 실패');}finally{setBusy(false);}}
 return <section className="section"><h2>내용 검수</h2><p>수집 정보와 공식 홈페이지를 대조한 뒤 승인하세요. 공간 경계 확인은 내용 확인과 별도로 기록합니다.</p><button type="button" onClick={load} disabled={busy}>검수 목록 조회</button>{message&&<p role="status">{message}</p>}{selected?<form className="review-form" onSubmit={save} key={selected.id}><h3>{selected.name}</h3><a className="text-link" href={`/${selected.kind}/${selected.id}`} target="_blank" rel="noopener noreferrer">상세 정보 확인 ↗</a><p>{selected.address}</p><label>검수자<input name="reviewer" required maxLength={100}/></label><label>확인한 출처·수정 또는 반려 사유<textarea name="note" required maxLength={2000}/></label><label><span><input type="checkbox" name="content_checked"/> 운영시간·요금·주소 등 내용을 확인했습니다</span></label><label><span><input type="checkbox" name="boundary_checked"/> 공식 행정구역 경계와 좌표의 일치를 확인했습니다</span></label>{Object.entries(labels).map(([key,label])=><div className="review-condition" key={key}><label>{label}<select name={key} defaultValue={selected.conditions[key]===true?'true':selected.conditions[key]===false?'false':'unknown'}><option value="unknown">미확인</option><option value="true">해당</option><option value="false">해당하지 않음</option></select></label><label>확인 근거 URL·공식 안내<input name={key+'_source'} defaultValue={selected.evidence[key]?.source||''} maxLength={2000}/></label></div>)}<div className="review-actions"><button value="approve" disabled={busy}>승인</button><button value="reject" className="reject" disabled={busy}>반려·공개 제외</button><button type="button" onClick={()=>setSelected(null)}>닫기</button></div></form>:<div className="review-list">{items.map(item=><article className="review-card" key={item.id}><strong>{item.name}</strong><p>{item.address}</p><p>{({pending:'검수 대기',approved:'승인',rejected:'반려'} as Record<string,string>)[item.status]||item.status} · 품질 {item.quality_score}{item.source_hidden?' · 원천 비공개':''}</p><button type="button" onClick={()=>setSelected(item)}>검수하기</button></article>)}</div>}</section>;
}
